spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/spring_examples_db?useSSL=false
    username: root
    password: test123
  
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
  
server:
  port: 8090